"""
Player panel detection configuration.
Auto-generated by calibrate_player.py — do not edit manually.
Re-run calibrate_player.py to recalibrate.
"""

INNATE_THRESHOLD = 0.75
FRAME_THRESHOLD  = 0.75

# All offsets relative to detected innate icon height (innate_h).
# Origin: innate icon top-left. Positive = right / down.
# pixel_offset = ratio * innate_h at detection time.

SKILL_1 = {'dx': 0.94, 'dy': 0.18, 'w': 1.08, 'h': 0.64}
LEVEL   = {'dx': -5.54, 'dy': 1.8, 'w': 0.78, 'h': 0.72}
ITEM_0  = {'dx': 8.74, 'dy': -0.1, 'w': 1.2, 'h': 0.9}  # from innate RIGHT edge — used by --update-frame

# Item grid: 2 rows × 3 cols, anchored from the panel frame (right anchor).
# FRAME_ITEMS_DX: from frame.x to right edge of column 2 (negative = items left of frame).
# FRAME_ITEMS_DY: from frame.y to top of row 0.
SLOT_W         = 1.2
SLOT_H         = 0.9
SLOT_GAP       = 0.08
SLOT_GAP_H_PX  = 2     # extra horizontal gap in absolute pixels
ITEMS_OFFSET_X = 3     # global horizontal shift for all item slots in absolute pixels
FRAME_ITEMS_DX = -1.1
FRAME_ITEMS_DY = -0.5
NUM_ITEM_SLOTS = 6
